# Generated by Django 4.2 on 2023-04-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0004_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_to_collection', models.TextField()),
                ('budget', models.IntegerField()),
                ('genres', models.TextField()),
                ('movie_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.DateTimeField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('tagline', models.TextField()),
                ('title', models.TextField()),
                ('production_companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.companies')),
                ('production_countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.countries')),
                ('spoken_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.languages')),
                ('votes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.votes')),
            ],
        ),
    ]
