# Generated by Django 4.2 on 2023-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0005_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.TextField(),
        ),
    ]
