# Generated by Django 4.2 on 2023-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0008_movies_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster_path',
            field=models.TextField(null=True),
        ),
    ]
