# Generated by Django 4.2 on 2023-04-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0010_cart_customer_order_lineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='movie',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.movies')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_go.zones')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='movie_go.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie_go.product'),
            preserve_default=False,
        ),
    ]
