# Generated by Django 4.2 on 2023-04-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0013_staffusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffUsers',
        ),
    ]
