# Generated by Django 4.2 on 2023-04-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0014_delete_staffusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
