# Generated by Django 4.2 on 2023-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0016_alter_customer_created_date_alter_order_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(null=True),
        ),
    ]
