# Generated by Django 4.2 on 2023-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_go', '0018_alter_customer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='booking_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='booking_time',
            field=models.CharField(max_length=100),
        ),
    ]
